name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: log event
        env: 
          GITHUB_CONTEXT: ${{ toJson(github.event) }} 
        run: echo "$GITHUB_CONTEXT" 
