name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: log event
        run: echo ${{ github.event.commits[0][message] }}
