name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - uses: actions/checkout@master
      - uses: fregante/setup-git-token@v1
        with:
          name: reservamosrobot
          email: action@github.com
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump package.json patch
        run: echo "tag=$(npm version patch)" >> $GITHUB_ENV

      - name: Push changes
        run: git push origin master

      - name: Upload release notes
        if: env.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          update_existing: true
          created_tag: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
