name: Create Release

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged && (
      contains(github.event.pull_request.labels.*.name, 'patch') ||
      contains(github.event.pull_request.labels.*.name, 'minor') ||
      contains(github.event.pull_request.labels.*.name, 'major'))
    steps:
      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.1'
      - uses: actions/checkout@master
      - uses: fregante/setup-git-token@v1
        with:
          name: reservamosrobot
          email: action@github.com
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: yarn and build
        run: yarn && yarn build

      - name: Commit build bundle
        run: |
          git add .
          git commit -m "adds build files"

      - name: Bump package.json patch
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: echo ::set-env name=tag::$(npm version patch)
      - name: Bump package.json minor
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: echo ::set-env name=tag::$(npm version minor)
      - name: Bump package.json major
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: echo ::set-env name=tag::$(npm version major)

      - name: Push changes
        run: git push origin master

      - name: Deploy to npm
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish --access private

      - name: Upload release notes
        if: env.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          update_existing: true
          created_tag: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
